# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(459, 554)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tableWidget_Proxy = QtWidgets.QTableWidget(self.tab)
        self.tableWidget_Proxy.setObjectName("tableWidget_Proxy")
        self.tableWidget_Proxy.setColumnCount(0)
        self.tableWidget_Proxy.setRowCount(0)
        self.verticalLayout_5.addWidget(self.tableWidget_Proxy)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 0, 0, 1, 1)
        self.lineEdit_Username = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_Username.setObjectName("lineEdit_Username")
        self.gridLayout_2.addWidget(self.lineEdit_Username, 1, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 0, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 0, 1, 1, 1)
        self.lineEdit_Password = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_Password.setObjectName("lineEdit_Password")
        self.gridLayout_2.addWidget(self.lineEdit_Password, 1, 2, 1, 1)
        self.lineEdit_IP = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_IP.setObjectName("lineEdit_IP")
        self.gridLayout_2.addWidget(self.lineEdit_IP, 1, 0, 1, 1)
        self.pushButton_Add_Proxy = QtWidgets.QPushButton(self.tab)
        self.pushButton_Add_Proxy.setObjectName("pushButton_Add_Proxy")
        self.gridLayout_2.addWidget(self.pushButton_Add_Proxy, 1, 3, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 2)
        self.gridLayout_2.setColumnStretch(1, 1)
        self.gridLayout_2.setColumnStretch(2, 1)
        self.gridLayout_2.setColumnStretch(3, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_Proxy_File = QtWidgets.QPushButton(self.tab)
        self.pushButton_Proxy_File.setObjectName("pushButton_Proxy_File")
        self.horizontalLayout_2.addWidget(self.pushButton_Proxy_File)
        self.label_Proxy_File = QtWidgets.QLabel(self.tab)
        self.label_Proxy_File.setObjectName("label_Proxy_File")
        self.horizontalLayout_2.addWidget(self.label_Proxy_File)
        self.pushButton_Import_Proxies = QtWidgets.QPushButton(self.tab)
        self.pushButton_Import_Proxies.setObjectName("pushButton_Import_Proxies")
        self.horizontalLayout_2.addWidget(self.pushButton_Import_Proxies)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 3)
        self.horizontalLayout_2.setStretch(2, 1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox_All_Proxies = QtWidgets.QCheckBox(self.tab)
        self.checkBox_All_Proxies.setObjectName("checkBox_All_Proxies")
        self.horizontalLayout.addWidget(self.checkBox_All_Proxies)
        self.pushButton_Export_Proxies = QtWidgets.QPushButton(self.tab)
        self.pushButton_Export_Proxies.setObjectName("pushButton_Export_Proxies")
        self.horizontalLayout.addWidget(self.pushButton_Export_Proxies)
        self.pushButton_Test_Proxy = QtWidgets.QPushButton(self.tab)
        self.pushButton_Test_Proxy.setObjectName("pushButton_Test_Proxy")
        self.horizontalLayout.addWidget(self.pushButton_Test_Proxy)
        self.pushButton_Delete_Proxy = QtWidgets.QPushButton(self.tab)
        self.pushButton_Delete_Proxy.setObjectName("pushButton_Delete_Proxy")
        self.horizontalLayout.addWidget(self.pushButton_Delete_Proxy)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.horizontalLayout_10.addLayout(self.verticalLayout_5)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_2.addWidget(self.label_10)
        self.tableWidget_Profile = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_Profile.setObjectName("tableWidget_Profile")
        self.tableWidget_Profile.setColumnCount(0)
        self.tableWidget_Profile.setRowCount(0)
        self.verticalLayout_2.addWidget(self.tableWidget_Profile)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.frame = QtWidgets.QFrame(self.tab_2)
        self.frame.setMinimumSize(QtCore.QSize(0, 200))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 2)
        self.lineEdit_Address1 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_Address1.setObjectName("lineEdit_Address1")
        self.gridLayout.addWidget(self.lineEdit_Address1, 2, 2, 1, 3)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 2)
        self.lineEdit_ProfileName = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_ProfileName.setObjectName("lineEdit_ProfileName")
        self.gridLayout.addWidget(self.lineEdit_ProfileName, 0, 2, 1, 1)
        self.lineEdit_LastName = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_LastName.setObjectName("lineEdit_LastName")
        self.gridLayout.addWidget(self.lineEdit_LastName, 1, 4, 1, 1)
        self.lineEdit_FirstName = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_FirstName.setObjectName("lineEdit_FirstName")
        self.gridLayout.addWidget(self.lineEdit_FirstName, 1, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 3, 1, 1)
        self.lineEdit_Address2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_Address2.setObjectName("lineEdit_Address2")
        self.gridLayout.addWidget(self.lineEdit_Address2, 3, 2, 1, 3)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.comboBox_Country = QtWidgets.QComboBox(self.frame)
        self.comboBox_Country.setCurrentText("")
        self.comboBox_Country.setObjectName("comboBox_Country")
        self.horizontalLayout_6.addWidget(self.comboBox_Country)
        self.comboBox_Province = QtWidgets.QComboBox(self.frame)
        self.comboBox_Province.setObjectName("comboBox_Province")
        self.horizontalLayout_6.addWidget(self.comboBox_Province)
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.lineEdit_City = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_City.setObjectName("lineEdit_City")
        self.horizontalLayout_6.addWidget(self.lineEdit_City)
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self.lineEdit_ZipCode = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_ZipCode.setObjectName("lineEdit_ZipCode")
        self.horizontalLayout_6.addWidget(self.lineEdit_ZipCode)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.lineEdit_Email = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_Email.setObjectName("lineEdit_Email")
        self.horizontalLayout_3.addWidget(self.lineEdit_Email)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_7.addWidget(self.label_9)
        self.lineEdit_Phone = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_Phone.setObjectName("lineEdit_Phone")
        self.horizontalLayout_7.addWidget(self.lineEdit_Phone)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButton_Save_Profile = QtWidgets.QPushButton(self.frame)
        self.pushButton_Save_Profile.setObjectName("pushButton_Save_Profile")
        self.horizontalLayout_8.addWidget(self.pushButton_Save_Profile)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.pushButton_Cancel_Profile = QtWidgets.QPushButton(self.frame)
        self.pushButton_Cancel_Profile.setObjectName("pushButton_Cancel_Profile")
        self.horizontalLayout_8.addWidget(self.pushButton_Cancel_Profile)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_3.addWidget(self.frame)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_NewProfile = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_NewProfile.setObjectName("pushButton_NewProfile")
        self.horizontalLayout_4.addWidget(self.pushButton_NewProfile)
        self.pushButton_Import_Profile = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_Import_Profile.setObjectName("pushButton_Import_Profile")
        self.horizontalLayout_4.addWidget(self.pushButton_Import_Profile)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.checkBox_All_Profiles = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_All_Profiles.setObjectName("checkBox_All_Profiles")
        self.horizontalLayout_4.addWidget(self.checkBox_All_Profiles)
        self.pushButton_Export_Profile = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_Export_Profile.setObjectName("pushButton_Export_Profile")
        self.horizontalLayout_4.addWidget(self.pushButton_Export_Profile)
        self.pushButton_Delete_Profile = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_Delete_Profile.setObjectName("pushButton_Delete_Profile")
        self.horizontalLayout_4.addWidget(self.pushButton_Delete_Profile)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_9.addLayout(self.verticalLayout_3)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.tab_3)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.tableWidget_Task = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget_Task.setObjectName("tableWidget_Task")
        self.tableWidget_Task.setColumnCount(0)
        self.tableWidget_Task.setRowCount(0)
        self.verticalLayout_10.addWidget(self.tableWidget_Task)
        self.frame_NewTask = QtWidgets.QFrame(self.tab_3)
        self.frame_NewTask.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_NewTask.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_NewTask.setObjectName("frame_NewTask")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_NewTask)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.frame_NewTask)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.tab_4)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.spinBox_BrowserNum = QtWidgets.QSpinBox(self.tab_4)
        self.spinBox_BrowserNum.setObjectName("spinBox_BrowserNum")
        self.gridLayout_3.addWidget(self.spinBox_BrowserNum, 1, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.tab_4)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 0, 1, 1, 1)
        self.comboBox_BrowserProxy = QtWidgets.QComboBox(self.tab_4)
        self.comboBox_BrowserProxy.setObjectName("comboBox_BrowserProxy")
        self.gridLayout_3.addWidget(self.comboBox_BrowserProxy, 1, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.tab_4)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 0, 0, 1, 1)
        self.lineEdit_BrowserUrl = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_BrowserUrl.setObjectName("lineEdit_BrowserUrl")
        self.gridLayout_3.addWidget(self.lineEdit_BrowserUrl, 3, 0, 1, 2)
        self.label_16 = QtWidgets.QLabel(self.tab_4)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 2, 0, 1, 2)
        self.verticalLayout_6.addLayout(self.gridLayout_3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem2)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.pushButton_Cancel_BrowserTask = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_Cancel_BrowserTask.setObjectName("pushButton_Cancel_BrowserTask")
        self.horizontalLayout_13.addWidget(self.pushButton_Cancel_BrowserTask)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem3)
        self.pushButton_Add_BrowserTask = QtWidgets.QPushButton(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Add_BrowserTask.sizePolicy().hasHeightForWidth())
        self.pushButton_Add_BrowserTask.setSizePolicy(sizePolicy)
        self.pushButton_Add_BrowserTask.setObjectName("pushButton_Add_BrowserTask")
        self.horizontalLayout_13.addWidget(self.pushButton_Add_BrowserTask)
        self.verticalLayout_6.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_11.addLayout(self.verticalLayout_6)
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.pushButton = QtWidgets.QPushButton(self.tab_5)
        self.pushButton.setGeometry(QtCore.QRect(30, 160, 56, 17))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_3.setGeometry(QtCore.QRect(310, 160, 56, 17))
        self.pushButton_3.setObjectName("pushButton_3")
        self.widget = QtWidgets.QWidget(self.tab_5)
        self.widget.setGeometry(QtCore.QRect(30, 10, 351, 36))
        self.widget.setObjectName("widget")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_20 = QtWidgets.QLabel(self.widget)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_7.addWidget(self.label_20)
        self.comboBox = QtWidgets.QComboBox(self.widget)
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout_7.addWidget(self.comboBox)
        self.horizontalLayout_14.addLayout(self.verticalLayout_7)
        self.label_19 = QtWidgets.QLabel(self.widget)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_14.addWidget(self.label_19)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_14.addWidget(self.lineEdit_3)
        self.widget1 = QtWidgets.QWidget(self.tab_5)
        self.widget1.setGeometry(QtCore.QRect(30, 110, 351, 36))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_17 = QtWidgets.QLabel(self.widget1)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_11.addWidget(self.label_17)
        self.comboBox_2 = QtWidgets.QComboBox(self.widget1)
        self.comboBox_2.setObjectName("comboBox_2")
        self.verticalLayout_11.addWidget(self.comboBox_2)
        self.horizontalLayout_17.addLayout(self.verticalLayout_11)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_18 = QtWidgets.QLabel(self.widget1)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_12.addWidget(self.label_18)
        self.comboBox_3 = QtWidgets.QComboBox(self.widget1)
        self.comboBox_3.setObjectName("comboBox_3")
        self.verticalLayout_12.addWidget(self.comboBox_3)
        self.horizontalLayout_17.addLayout(self.verticalLayout_12)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_23 = QtWidgets.QLabel(self.widget1)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_13.addWidget(self.label_23)
        self.spinBox = QtWidgets.QSpinBox(self.widget1)
        self.spinBox.setObjectName("spinBox")
        self.verticalLayout_13.addWidget(self.spinBox)
        self.horizontalLayout_17.addLayout(self.verticalLayout_13)
        self.widget2 = QtWidgets.QWidget(self.tab_5)
        self.widget2.setGeometry(QtCore.QRect(30, 60, 351, 32))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_21 = QtWidgets.QLabel(self.widget2)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_8.addWidget(self.label_21)
        self.lineEdit = QtWidgets.QLineEdit(self.widget2)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_8.addWidget(self.lineEdit)
        self.horizontalLayout_18.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_22 = QtWidgets.QLabel(self.widget2)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_9.addWidget(self.label_22)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget2)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_9.addWidget(self.lineEdit_2)
        self.horizontalLayout_18.addLayout(self.verticalLayout_9)
        self.tabWidget_2.addTab(self.tab_5, "")
        self.horizontalLayout_15.addWidget(self.tabWidget_2)
        self.verticalLayout_10.addWidget(self.frame_NewTask)
        self.frame_BrowserAction = QtWidgets.QFrame(self.tab_3)
        self.frame_BrowserAction.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_BrowserAction.setStyleSheet("")
        self.frame_BrowserAction.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_BrowserAction.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_BrowserAction.setObjectName("frame_BrowserAction")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.frame_BrowserAction)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_24 = QtWidgets.QLabel(self.frame_BrowserAction)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_14.addWidget(self.label_24)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushButton_Browser_Refresh = QtWidgets.QPushButton(self.frame_BrowserAction)
        self.pushButton_Browser_Refresh.setObjectName("pushButton_Browser_Refresh")
        self.gridLayout_4.addWidget(self.pushButton_Browser_Refresh, 1, 0, 1, 1)
        self.pushButton_Browser_Back = QtWidgets.QPushButton(self.frame_BrowserAction)
        self.pushButton_Browser_Back.setObjectName("pushButton_Browser_Back")
        self.gridLayout_4.addWidget(self.pushButton_Browser_Back, 1, 1, 1, 1)
        self.pushButton_Browser_Forward = QtWidgets.QPushButton(self.frame_BrowserAction)
        self.pushButton_Browser_Forward.setObjectName("pushButton_Browser_Forward")
        self.gridLayout_4.addWidget(self.pushButton_Browser_Forward, 1, 2, 1, 1)
        self.pushButton_Browser_DeleteCookie = QtWidgets.QPushButton(self.frame_BrowserAction)
        self.pushButton_Browser_DeleteCookie.setObjectName("pushButton_Browser_DeleteCookie")
        self.gridLayout_4.addWidget(self.pushButton_Browser_DeleteCookie, 1, 3, 1, 1)
        self.pushButton_Goto_NewUrl = QtWidgets.QPushButton(self.frame_BrowserAction)
        self.pushButton_Goto_NewUrl.setObjectName("pushButton_Goto_NewUrl")
        self.gridLayout_4.addWidget(self.pushButton_Goto_NewUrl, 0, 3, 1, 1)
        self.lineEdit_NewUrl = QtWidgets.QLineEdit(self.frame_BrowserAction)
        self.lineEdit_NewUrl.setObjectName("lineEdit_NewUrl")
        self.gridLayout_4.addWidget(self.lineEdit_NewUrl, 0, 0, 1, 3)
        self.verticalLayout_14.addLayout(self.gridLayout_4)
        self.horizontalLayout_19.addLayout(self.verticalLayout_14)
        self.verticalLayout_10.addWidget(self.frame_BrowserAction)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.pushButton_NewTask = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_NewTask.setObjectName("pushButton_NewTask")
        self.horizontalLayout_12.addWidget(self.pushButton_NewTask)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem4)
        self.checkBox_All_Tasks = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_All_Tasks.setObjectName("checkBox_All_Tasks")
        self.horizontalLayout_12.addWidget(self.checkBox_All_Tasks)
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_12.addWidget(self.pushButton_2)
        self.pushButton_Delete_Task = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_Delete_Task.setObjectName("pushButton_Delete_Task")
        self.horizontalLayout_12.addWidget(self.pushButton_Delete_Task)
        self.pushButton_Start_Tasks = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_Start_Tasks.setObjectName("pushButton_Start_Tasks")
        self.horizontalLayout_12.addWidget(self.pushButton_Start_Tasks)
        self.pushButton_Stop_Tasks = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_Stop_Tasks.setObjectName("pushButton_Stop_Tasks")
        self.horizontalLayout_12.addWidget(self.pushButton_Stop_Tasks)
        self.verticalLayout_10.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_16.addLayout(self.verticalLayout_10)
        self.tabWidget.addTab(self.tab_3, "")
        self.horizontalLayout_5.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 459, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_11.setText(_translate("MainWindow", "IP"))
        self.label_13.setText(_translate("MainWindow", "Password"))
        self.label_12.setText(_translate("MainWindow", "Username"))
        self.pushButton_Add_Proxy.setText(_translate("MainWindow", "添加"))
        self.pushButton_Proxy_File.setText(_translate("MainWindow", "选择文件"))
        self.label_Proxy_File.setText(_translate("MainWindow", "文件路径"))
        self.pushButton_Import_Proxies.setText(_translate("MainWindow", "导入"))
        self.checkBox_All_Proxies.setText(_translate("MainWindow", "全选"))
        self.pushButton_Export_Proxies.setText(_translate("MainWindow", "导出"))
        self.pushButton_Test_Proxy.setText(_translate("MainWindow", "测试"))
        self.pushButton_Delete_Proxy.setText(_translate("MainWindow", "删除选中"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Proxy"))
        self.label_10.setText(_translate("MainWindow", "Profiles"))
        self.label_5.setText(_translate("MainWindow", "Address 1"))
        self.label_6.setText(_translate("MainWindow", "Address 2"))
        self.label_2.setText(_translate("MainWindow", "Profile Name"))
        self.label_4.setText(_translate("MainWindow", "Last Name"))
        self.label_3.setText(_translate("MainWindow", "First Name"))
        self.label_7.setText(_translate("MainWindow", "City"))
        self.label_8.setText(_translate("MainWindow", "ZIP code"))
        self.label.setText(_translate("MainWindow", "Email"))
        self.label_9.setText(_translate("MainWindow", "Phone"))
        self.pushButton_Save_Profile.setText(_translate("MainWindow", "保存"))
        self.pushButton_Cancel_Profile.setText(_translate("MainWindow", "取消"))
        self.pushButton_NewProfile.setText(_translate("MainWindow", "新建"))
        self.pushButton_Import_Profile.setText(_translate("MainWindow", "导入"))
        self.checkBox_All_Profiles.setText(_translate("MainWindow", "全选"))
        self.pushButton_Export_Profile.setText(_translate("MainWindow", "导出"))
        self.pushButton_Delete_Profile.setText(_translate("MainWindow", "删除"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Profile"))
        self.label_15.setText(_translate("MainWindow", "Num"))
        self.label_14.setText(_translate("MainWindow", "Proxy IP"))
        self.label_16.setText(_translate("MainWindow", "Url"))
        self.pushButton_Cancel_BrowserTask.setText(_translate("MainWindow", "取消"))
        self.pushButton_Add_BrowserTask.setText(_translate("MainWindow", "添加任务"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "浏览器多开"))
        self.pushButton.setText(_translate("MainWindow", "取消"))
        self.pushButton_3.setText(_translate("MainWindow", "添加任务"))
        self.label_20.setText(_translate("MainWindow", "Store"))
        self.label_19.setText(_translate("MainWindow", "URL"))
        self.label_17.setText(_translate("MainWindow", "Poxy"))
        self.label_18.setText(_translate("MainWindow", "Profile"))
        self.label_23.setText(_translate("MainWindow", "Num"))
        self.label_21.setText(_translate("MainWindow", "Keyword"))
        self.label_22.setText(_translate("MainWindow", "Size"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "shopify"))
        self.label_24.setText(_translate("MainWindow", "浏览器批量操作"))
        self.pushButton_Browser_Refresh.setText(_translate("MainWindow", "刷新"))
        self.pushButton_Browser_Back.setText(_translate("MainWindow", "后退"))
        self.pushButton_Browser_Forward.setText(_translate("MainWindow", "前进"))
        self.pushButton_Browser_DeleteCookie.setText(_translate("MainWindow", "清cookie"))
        self.pushButton_Goto_NewUrl.setText(_translate("MainWindow", "访问"))
        self.pushButton_NewTask.setText(_translate("MainWindow", "新建任务"))
        self.checkBox_All_Tasks.setText(_translate("MainWindow", "全选"))
        self.pushButton_2.setText(_translate("MainWindow", "修改任务"))
        self.pushButton_Delete_Task.setText(_translate("MainWindow", "删除任务"))
        self.pushButton_Start_Tasks.setText(_translate("MainWindow", "开始任务"))
        self.pushButton_Stop_Tasks.setText(_translate("MainWindow", "结束任务"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Task"))
